---
name: Release qnapexporter

on: # yamllint disable-line rule:truthy
  release:
    types: [created]

jobs:
  release-qnapexporter:
    name: release qnapexporter
    runs-on: self-hosted
    strategy:
      matrix:
        # build and publish in parallel: linux/386, linux/amd64, linux/arm64, windows/386, windows/amd64, darwin/amd64, darwin/arm64
        goos: [linux]
        goarch: [amd64, arm64, arm]
    permissions:
      contents: write # for wangyoucao577/go-release-action to upload assets
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
            
      - uses: wangyoucao577/go-release-action@v1.51
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          build_command: make build PACKAGE_VERSION="$GITHUB_REF_NAME"
          binary_name: bin/qnapexporter
          asset_name: qnapexporter-${{ matrix.goos }}-${{ matrix.goarch }}
          overwrite: true
